# Name of the file (without its extension) in "lang" directory,
# that will be used for the messages translations.
# You can create a custom file, with your language, inside the directory and use it there.
language: en

# If it's true, the plugin will remove kb resistance
# on all netherite armor items.
remove-netherite-kb-resistance: true

# Plugin blacklist
# A blacklisted item can be force updated with the /fix-attributes command, but
# it will not be updated automatically when the different events are called.
# Write the item material in capital letters, like "DIAMOND_HELMET" for example.
blacklist:
  - ""