name: CombatAttributes
version: '${project.version}'
main: fr.keykatyu.combatattributes.Main
api-version: '1.20'
authors: [KeyKatyu]
description: '${project.description}'
softdepend:
  - ExecutableItems
  - SCore
commands:
  fix-attributes:
    description: Fix items attributes and update lore